import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: {
          DEFAULT: 'rgb(var(--background) / <alpha-value>)',
          5: 'rgb(var(--background) / 0.05)',
          10: 'rgb(var(--background) / 0.1)',
          15: 'rgb(var(--background) / 0.15)',
          20: 'rgb(var(--background) / 0.2)',
          30: 'rgb(var(--background) / 0.3)',
          50: 'rgb(var(--background) / 0.5)',
          70: 'rgb(var(--background) / 0.7)',
          87: 'rgb(var(--background) / 0.87)',
          90: 'rgb(var(--background) / 0.9)',
          95: 'rgb(var(--background) / 0.95)',
        },
        foreground: {
          DEFAULT: 'rgb(var(--foreground) / <alpha-value>)',
          5: 'rgb(var(--foreground) / 0.05)',
          10: 'rgb(var(--foreground) / 0.1)',
          15: 'rgb(var(--foreground) / 0.15)',
          20: 'rgb(var(--foreground) / 0.2)',
          30: 'rgb(var(--foreground) / 0.3)',
          50: 'rgb(var(--foreground) / 0.5)',
          70: 'rgb(var(--foreground) / 0.7)',
          87: 'rgb(var(--foreground) / 0.87)',
          90: 'rgb(var(--foreground) / 0.9)',
          95: 'rgb(var(--foreground) / 0.95)',
        },
        card: {
          DEFAULT: 'rgb(var(--card) / <alpha-value>)',
          foreground: 'rgb(var(--card-foreground) / <alpha-value>)',
          5: 'rgb(var(--card) / 0.05)',
          10: 'rgb(var(--card) / 0.1)',
          15: 'rgb(var(--card) / 0.15)',
          20: 'rgb(var(--card) / 0.2)',
          30: 'rgb(var(--card) / 0.3)',
          50: 'rgb(var(--card) / 0.5)',
          70: 'rgb(var(--card) / 0.7)',
          87: 'rgb(var(--card) / 0.87)',
          90: 'rgb(var(--card) / 0.9)',
          95: 'rgb(var(--card) / 0.95)',
        },
        popover: {
          DEFAULT: 'rgb(var(--popover) / <alpha-value>)',
          foreground: 'rgb(var(--popover-foreground) / <alpha-value>)',
          5: 'rgb(var(--popover) / 0.05)',
          10: 'rgb(var(--popover) / 0.1)',
          15: 'rgb(var(--popover) / 0.15)',
          20: 'rgb(var(--popover) / 0.2)',
          30: 'rgb(var(--popover) / 0.3)',
          50: 'rgb(var(--popover) / 0.5)',
          70: 'rgb(var(--popover) / 0.7)',
          87: 'rgb(var(--popover) / 0.87)',
          90: 'rgb(var(--popover) / 0.9)',
          95: 'rgb(var(--popover) / 0.95)',
        },
        primary: {
          DEFAULT: 'rgb(var(--primary) / <alpha-value>)',
          foreground: 'rgb(var(--primary-foreground) / <alpha-value>)',
          hover: 'rgb(var(--primary-hover) / <alpha-value>)',
          'hover-text': 'rgb(var(--primary-hover-text) / <alpha-value>)',
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        secondary: {
          DEFAULT: 'rgb(var(--secondary) / <alpha-value>)',
          foreground: 'rgb(var(--secondary-foreground) / <alpha-value>)',
          5: 'rgb(var(--secondary) / 0.05)',
          10: 'rgb(var(--secondary) / 0.1)',
          15: 'rgb(var(--secondary) / 0.15)',
          20: 'rgb(var(--secondary) / 0.2)',
          30: 'rgb(var(--secondary) / 0.3)',
          50: 'rgb(var(--secondary) / 0.5)',
          70: 'rgb(var(--secondary) / 0.7)',
          87: 'rgb(var(--secondary) / 0.87)',
          90: 'rgb(var(--secondary) / 0.9)',
          95: 'rgb(var(--secondary) / 0.95)',
        },
        'secondary-bg': {
          DEFAULT: 'rgb(var(--secondary-bg) / <alpha-value>)',
          5: 'rgb(var(--secondary-bg) / 0.05)',
          10: 'rgb(var(--secondary-bg) / 0.1)',
          15: 'rgb(var(--secondary-bg) / 0.15)',
          20: 'rgb(var(--secondary-bg) / 0.2)',
          30: 'rgb(var(--secondary-bg) / 0.3)',
          50: 'rgb(var(--secondary-bg) / 0.5)',
          70: 'rgb(var(--secondary-bg) / 0.7)',
          87: 'rgb(var(--secondary-bg) / 0.87)',
          90: 'rgb(var(--secondary-bg) / 0.9)',
          95: 'rgb(var(--secondary-bg) / 0.95)',
        },
        muted: {
          DEFAULT: 'rgb(var(--muted) / <alpha-value>)',
          foreground: 'rgb(var(--muted-foreground) / <alpha-value>)',
          5: 'rgb(var(--muted) / 0.05)',
          10: 'rgb(var(--muted) / 0.1)',
          15: 'rgb(var(--muted) / 0.15)',
          20: 'rgb(var(--muted) / 0.2)',
          30: 'rgb(var(--muted) / 0.3)',
          50: 'rgb(var(--muted) / 0.5)',
          70: 'rgb(var(--muted) / 0.7)',
          87: 'rgb(var(--muted) / 0.87)',
          90: 'rgb(var(--muted) / 0.9)',
          95: 'rgb(var(--muted) / 0.95)',
        },
        accent: {
          DEFAULT: 'rgb(var(--accent) / <alpha-value>)',
          foreground: 'rgb(var(--accent-foreground) / <alpha-value>)',
          5: 'rgb(var(--accent) / 0.05)',
          10: 'rgb(var(--accent) / 0.1)',
          15: 'rgb(var(--accent) / 0.15)',
          20: 'rgb(var(--accent) / 0.2)',
          30: 'rgb(var(--accent) / 0.3)',
          50: 'rgb(var(--accent) / 0.5)',
          70: 'rgb(var(--accent) / 0.7)',
          87: 'rgb(var(--accent) / 0.87)',
          90: 'rgb(var(--accent) / 0.9)',
          95: 'rgb(var(--accent) / 0.95)',
        },
        destructive: {
          DEFAULT: 'rgb(var(--destructive) / <alpha-value>)',
          foreground: 'rgb(var(--destructive-foreground) / <alpha-value>)',
          5: 'rgb(var(--destructive) / 0.05)',
          10: 'rgb(var(--destructive) / 0.1)',
          15: 'rgb(var(--destructive) / 0.15)',
          20: 'rgb(var(--destructive) / 0.2)',
          30: 'rgb(var(--destructive) / 0.3)',
          50: 'rgb(var(--destructive) / 0.5)',
          70: 'rgb(var(--destructive) / 0.7)',
          87: 'rgb(var(--destructive) / 0.87)',
          90: 'rgb(var(--destructive) / 0.9)',
          95: 'rgb(var(--destructive) / 0.95)',
        },
        border: {
          DEFAULT: 'rgb(var(--border) / <alpha-value>)',
          5: 'rgb(var(--border) / 0.05)',
          10: 'rgb(var(--border) / 0.1)',
          15: 'rgb(var(--border) / 0.15)',
          20: 'rgb(var(--border) / 0.2)',
          30: 'rgb(var(--border) / 0.3)',
          50: 'rgb(var(--border) / 0.5)',
          70: 'rgb(var(--border) / 0.7)',
          87: 'rgb(var(--border) / 0.87)',
          90: 'rgb(var(--border) / 0.9)',
          95: 'rgb(var(--border) / 0.95)',
        },
        input: {
          DEFAULT: 'rgb(var(--input) / <alpha-value>)',
          5: 'rgb(var(--input) / 0.05)',
          10: 'rgb(var(--input) / 0.1)',
          15: 'rgb(var(--input) / 0.15)',
          20: 'rgb(var(--input) / 0.2)',
          30: 'rgb(var(--input) / 0.3)',
          50: 'rgb(var(--input) / 0.5)',
          70: 'rgb(var(--input) / 0.7)',
          87: 'rgb(var(--input) / 0.87)',
          90: 'rgb(var(--input) / 0.9)',
          95: 'rgb(var(--input) / 0.95)',
        },
        'select-bg': {
          DEFAULT: 'rgb(var(--select-bg) / <alpha-value>)',
          5: 'rgb(var(--select-bg) / 0.05)',
          8: 'rgb(var(--select-bg) / 0.08)',
          10: 'rgb(var(--select-bg) / 0.1)',
        },
        ring: {
          DEFAULT: 'rgb(var(--ring) / <alpha-value>)',
          5: 'rgb(var(--ring) / 0.05)',
          10: 'rgb(var(--ring) / 0.1)',
          15: 'rgb(var(--ring) / 0.15)',
          20: 'rgb(var(--ring) / 0.2)',
          30: 'rgb(var(--ring) / 0.3)',
          50: 'rgb(var(--ring) / 0.5)',
          70: 'rgb(var(--ring) / 0.7)',
          87: 'rgb(var(--ring) / 0.87)',
          90: 'rgb(var(--ring) / 0.9)',
          95: 'rgb(var(--ring) / 0.95)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      animation: {
        blink: 'blink 1s infinite',
        spin: 'spin 1s linear infinite',
      },
      keyframes: {
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};

export default config;
